# Generated by Django 4.0.4 on 2022-09-07 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('province', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('ward', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('building', models.CharField(max_length=50)),
                ('house_no', models.CharField(max_length=50)),
                ('used', models.BooleanField(default=True)),
            ],
        ),
    ]
