# Generated by Django 4.0.4 on 2022-09-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('province', '0003_address_first_name_address_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='code',
            field=models.IntegerField(unique=True),
        ),
    ]
