# Generated by Django 4.0.4 on 2022-09-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('province', '0006_alter_department_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='isActived',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='department',
            name='eng_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='isActived',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='site',
            name='isActived',
            field=models.BooleanField(default=True),
        ),
    ]
