# Generated by Django 4.0.4 on 2022-09-10 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('province', '0007_company_isactived_department_eng_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationshipPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=20, null=True)),
                ('middlename', models.CharField(blank=True, max_length=20, null=True)),
                ('lastname', models.CharField(blank=True, max_length=20, null=True)),
                ('cmnd_no', models.CharField(blank=True, max_length=20, null=True)),
                ('cccd_no', models.CharField(blank=True, max_length=20, null=True)),
                ('dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=20, null=True)),
                ('middlename', models.CharField(blank=True, max_length=20, null=True)),
                ('lastname', models.CharField(blank=True, max_length=20, null=True)),
                ('cmnd_no', models.CharField(blank=True, max_length=20, null=True)),
                ('cccd_no', models.CharField(blank=True, max_length=20, null=True)),
                ('dob', models.DateField()),
                ('is_Staff', models.BooleanField(default=True)),
                ('nguoi_than', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='province.relationshipperson')),
                ('phongban', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='province.department')),
            ],
        ),
    ]
