# Generated by Django 4.0.4 on 2022-09-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('province', '0010_person_gender_relationshipperson_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='lastname',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='relationshipperson',
            name='moi_quan_he',
            field=models.CharField(blank=True, choices=[('BV', 'Ba Vợ'), ('MV', 'Mẹ Vợ'), ('BR', 'Ba Ruột'), ('MR', 'Mẹ Ruột'), ('BC', 'Ba Chồng'), ('MC', 'Mẹ Chồng'), ('CO', 'Con'), ('VO', 'Vợ')], max_length=20, null=True),
        ),
    ]
