# Generated by Django 4.0.4 on 2022-09-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('province', '0011_person_code_alter_person_lastname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='vo_chung_cty',
            field=models.BooleanField(default=False),
        ),
    ]
