# Generated by Django 4.0.4 on 2022-09-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('province', '0012_person_vo_chung_cty'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationshipperson',
            name='is_Staff',
            field=models.BooleanField(default=False),
        ),
    ]
