# Generated by Django 4.0.4 on 2022-09-11 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('province', '0013_relationshipperson_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='middle_name',
        ),
        migrations.AddField(
            model_name='person',
            name='addresses',
            field=models.ManyToManyField(to='province.address'),
        ),
        migrations.AlterField(
            model_name='relationshipperson',
            name='moi_quan_he',
            field=models.CharField(blank=True, choices=[('BV', 'Ba Vợ'), ('MV', 'Mẹ Vợ'), ('BR', 'Ba Ruột'), ('MR', 'Mẹ Ruột'), ('BC', 'Ba Chồng'), ('MC', 'Mẹ Chồng'), ('CO', 'Con'), ('VO', 'Vợ'), ('CH', 'Chồng')], max_length=20, null=True),
        ),
    ]
