# Generated by Django 4.0.4 on 2022-09-11 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('province', '0014_remove_address_first_name_remove_address_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='building',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
