# Generated by Django 4.0.4 on 2022-09-11 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('province', '0015_alter_address_building'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_type', models.CharField(choices=[('CCN', 'Chống cháy nổi'), ('EXT', 'Điện thoại nội bộ')], max_length=5)),
                ('isActived', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrivatePhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20, null=True)),
                ('isActived', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='relationshipperson',
            name='addresses',
            field=models.ManyToManyField(to='province.address'),
        ),
        migrations.AddField(
            model_name='person',
            name='private_phone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='province.privatephone'),
        ),
        migrations.AddField(
            model_name='relationshipperson',
            name='company_phone',
            field=models.ManyToManyField(to='province.companyphone'),
        ),
        migrations.AddField(
            model_name='relationshipperson',
            name='private_phone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='province.privatephone'),
        ),
    ]
