# Generated by Django 4.0.4 on 2022-09-11 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('province', '0016_companyphone_privatephone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationshipperson',
            name='company_phone',
        ),
        migrations.AddField(
            model_name='person',
            name='company_phone',
            field=models.ManyToManyField(to='province.companyphone'),
        ),
    ]
