# Generated by Django 4.0.4 on 2022-09-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('province', '0017_remove_relationshipperson_company_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('short_name', models.CharField(blank=True, max_length=20, null=True)),
                ('is_actived', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='position',
            field=models.ManyToManyField(to='province.position'),
        ),
    ]
